platform :ios, '7.0'

pod 'SDWebImage', '~> 3.7.1'
pod 'Toast', '~> 2.4'
pod 'SVProgressHUD', '~> 1.1.2'
pod 'M80AttributedLabel', '~> 1.3.1'
pod 'FMDB', '~> 2.5'
pod 'Reachability', '~> 3.1.1'
pod 'CocoaLumberjack', '~> 2.0.0-rc2'
pod 'SSZipArchive', '~> 1.2’